Repository kaipartmann/Peridynamics.jl, pull requests merged in 2024-10, with the labels that each got.

#175 New point generator functions
  Project.toml
  docs/src/api_reference.md
  docs/src/literate/tutorial_logo.jl
  src/Peridynamics.jl
  src/auxiliary/precompile_workload.jl
  src/discretization/point_generators.jl
  test/auxiliary/test_io.jl
  test/discretization/test_point_generators.jl
Labels: enhancement, breaking

#179 Enhancements to point parameters
  src/Peridynamics.jl
  src/auxiliary/errors.jl
  src/core/parameters.jl
  src/core/systems.jl
  src/discretization/bond_system.jl
  src/discretization/interaction_system.jl
  src/physics/bond_based.jl
  src/physics/continuum_kinematics_inspired.jl
  src/physics/correspondence.jl
  src/physics/fracture.jl
  src/physics/material_parameters.jl
  src/physics/ordinary_state_based.jl
  test/auxiliary/test_errors.jl
  test/auxiliary/test_io.jl
  test/integration/material_interface.jl
  test/integration/mpi_threads_comparison.jl
  test/integration/symmetry_bond_based.jl
  test/integration/symmetry_continuum_inspired.jl
  test/integration/symmetry_correspondence.jl
  test/integration/symmetry_ordinary_state_based.jl
  test/integration/test_material.jl
  test/physics/test_bond_based.jl
  test/physics/test_material_parameters.jl
Labels: enhancement, breaking, refactoring

#180 Enhancements to storages
  src/Peridynamics.jl
  src/auxiliary/generator_functions.jl
  src/auxiliary/io.jl
  src/core/mpi_body_data_handler.jl
  src/core/storages.jl
  src/core/systems.jl
  src/core/threads_body_data_handler.jl
  src/core/threads_multibody_data_handler.jl
  src/core/time_solvers.jl
  src/discretization/body.jl
  src/discretization/body_chunk.jl
  src/discretization/bond_system.jl
  src/discretization/chunk_handler.jl
  src/discretization/interaction_system.jl
  src/discretization/predefined_cracks.jl
  src/physics/bond_based.jl
  src/physics/continuum_kinematics_inspired.jl
  src/physics/correspondence.jl
  src/physics/fracture.jl
  src/physics/ordinary_state_based.jl
  src/time_solvers/dynamic_relaxation.jl
  src/time_solvers/velocity_verlet.jl
  test/VtkReader/test_read_vtk.jl
  test/core/test_fracture.jl
  test/core/test_storages.jl
  test/core/test_time_solvers.jl
  test/discretization/test_body_chunk.jl
  test/discretization/test_bond_discretization.jl
  test/discretization/test_interaction_system.jl
  test/integration/material_interface.jl
  test/integration/predefined_cracks.jl
  test/integration/test_material.jl
  test/physics/test_bond_based.jl
Labels: enhancement, refactoring

#184 Add solver dependent storage macro
  src/core/parameters.jl
  src/core/storages.jl
  test/integration/material_interface.jl
Labels: enhancement
