Repository kaipartmann/Peridynamics.jl, pull requests merged in 2024-07, with the labels that each got.

#130 Interface bug
  src/core/parameter_handler.jl
  src/core/storages.jl
  src/discretization/bond_system.jl
  src/discretization/bond_system_corrections.jl
  src/discretization/interaction_system.jl
  src/physics/bond_based.jl
  src/physics/continuum_kinematics_inspired.jl
  src/physics/correspondence.jl
  src/physics/ordinary_state_based.jl
  test/discretization/test_body_chunk.jl
  test/integration/b_int_bond_based.jl
  test/integration/b_int_continuum_inspired.jl
  test/integration/b_int_correspondence.jl
  test/integration/b_int_ordinary_state_based.jl
  test/integration/energy_surface_correction.jl
Labels: bug

#135 PointNeighbors.jl update
  Project.toml
  src/discretization/bond_system.jl
  src/physics/short_range_force_contact.jl
  test/discretization/test_bond_discretization.jl
Labels: dependencies

#136 Create Body from Abaqus file directly
  docs/src/api_public.md
  src/AbaqusMeshConverter/AbaqusMeshConverter.jl
  src/Peridynamics.jl
  src/discretization/body.jl
  src/discretization/point_sets.jl
  test/AbaqusMeshConverter/test_AbaqusMeshConverter.jl
  test/discretization/test_body.jl
Labels: enhancement

#137 Printing and logging enhancements
  src/auxiliary/logs.jl
  src/core/submit.jl
  src/discretization/body.jl
  test/auxiliary/test_logs.jl
Labels: enhancement

#140 VTK file name `_` bug
  src/auxiliary/io.jl
  src/core/job.jl
  src/core/mpi_body_data_handler.jl
  src/core/threads_body_data_handler.jl
  src/core/threads_multibody_data_handler.jl
  src/discretization/body.jl
  src/discretization/multibody_setup.jl
  src/time_solvers/velocity_verlet.jl
  test/auxiliary/test_io.jl
  test/integration/symmetry_bond_based.jl
Labels: bug

#141 Internal enhancements to conditions
  src/Peridynamics.jl
  src/auxiliary/logs.jl
  src/conditions/condition_checks.jl
  src/conditions/initial_conditions.jl
  src/discretization/body.jl
  src/discretization/point_sets.jl
  src/discretization/predefined_cracks.jl
  src/physics/boundary_conditions.jl
  src/physics/initial_conditions.jl
  src/time_solvers/dynamic_relaxation.jl
  src/time_solvers/velocity_verlet.jl
  test/conditions/test_boundary_conditions.jl
  test/discretization/test_body.jl
  test/physics/test_conditions.jl
Labels: enhancement

#143 Added a separate function for the influence function
  src/physics/correspondence.jl
  src/physics/ordinary_state_based.jl
Labels: enhancement

#145 Tutorial Logo
  docs/make.jl
  docs/src/literate/tutorial_logo.jl
Labels: documentation

#149 Add multibody problem to precompilation
  src/auxiliary/precompile_workload.jl
Labels: enhancement

#148 [Documentation] Tutorial Kalthoff-Winkler
  .gitignore
  README.md
  docs/make.jl
  docs/src/index.md
  docs/src/literate/tutorial_kalthoff-winkler_dynfrac.jl
Labels: documentation

#153 Change multithreading backend to Base.Threads
  CITATION.cff
  Project.toml
  src/Peridynamics.jl
  src/VtkReader/VtkReader.jl
  src/auxiliary/process_each_export.jl
  src/core/threads_body_data_handler.jl
  src/core/threads_multibody_data_handler.jl
  src/discretization/bond_system_corrections.jl
  src/physics/short_range_force_contact.jl
  src/time_solvers/dynamic_relaxation.jl
  src/time_solvers/velocity_verlet.jl
Labels: performance, parallelization, dependencies
