Repository kaipartmann/Peridynamics.jl, pull requests merged in 2025-04, with the labels that each got.

#192 Add flexible boundary condition handling via matrix
  docs/src/private_api_reference.md
  src/discretization/body.jl
  src/discretization/body_chunk.jl
  src/physics/boundary_conditions.jl
  test/integration/data_boundary_conditions.jl
  test/integration/uniform_tension_dynamic_relaxation.jl
  test/physics/test_conditions.jl
Labels: enhancement

#203 Private API
  docs/src/private_api_reference.md
  src/AbaqusMeshConverter/AbaqusMeshConverter.jl
  src/VtkReader/VtkReader.jl
  src/auxiliary/docs.jl
  src/auxiliary/errors.jl
  src/core/halo_exchange.jl
  src/core/job.jl
  src/core/mpi_body_data_handler.jl
  src/core/parameter_handler.jl
  src/core/parameters.jl
  src/core/storages.jl
  src/core/threads_body_data_handler.jl
  src/core/threads_multibody_data_handler.jl
  src/discretization/body.jl
  src/discretization/body_chunk.jl
  src/discretization/bond_system.jl
  src/discretization/chunk_handler.jl
  src/discretization/decomposition.jl
  src/discretization/interaction_system.jl
  src/discretization/multibody_setup.jl
  src/discretization/point_generators.jl
  src/discretization/point_sets.jl
  src/discretization/predefined_cracks.jl
  src/physics/ba_correspondence.jl
  src/physics/bond_based.jl
  src/physics/boundary_conditions.jl
  src/physics/continuum_kinematics_inspired.jl
  src/physics/correspondence.jl
  src/physics/fracture.jl
  src/physics/initial_conditions.jl
  src/physics/material_parameters.jl
  src/physics/ordinary_state_based.jl
  src/physics/short_range_force_contact.jl
  src/time_solvers/dynamic_relaxation.jl
  src/time_solvers/velocity_verlet.jl
Labels: documentation

#211 Improved testing
  src/auxiliary/generator_functions.jl
  src/core/storages.jl
  test/auxiliary/test_mpi.jl
  test/auxiliary/test_process_each_export.jl
  test/core/test_halo_exchange.jl
  test/core/test_storages.jl
  test/integration/b_int_bond_based.jl
  test/integration/mpi_threads_comparison.jl
  test/runtests.jl
Labels: parallelization, tests
