Repository kaipartmann/Peridynamics.jl, pull requests merged in 2025-05, with the labels that each got.

#217 Fix broken example block in docstring
  src/core/storages.jl
Labels: documentation

#219 Added the ZEM algorithm of Wan et al. (2019).
  docs/src/public_api_reference.md
  src/Peridynamics.jl
  src/discretization/zem_stabilization.jl
  src/physics/constitutive_models.jl
  src/physics/correspondence.jl
  src/physics/correspondence_rotated.jl
  test/discretization/test_bond_system.jl
  test/integration/b_int_correspondence.jl
Labels: enhancement

#223 Additional tests for specific material models
  test/discretization/test_bond_associated_system.jl
  test/discretization/test_interaction_system.jl
Labels: tests
